// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/cicbyte/aic/internal/dao/internal"
)

// skillTagsDao is the data access object for the table skill_tags.
// You can define custom methods on it to extend its functionality as needed.
type skillTagsDao struct {
	*internal.SkillTagsDao
}

var (
	// SkillTags is a globally accessible object for table skill_tags operations.
	SkillTags = skillTagsDao{internal.NewSkillTagsDao()}
)

// Add your custom methods and functionality below.
