// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/cicbyte/aic/internal/dao/internal"
)

// skillsDao is the data access object for the table skills.
// You can define custom methods on it to extend its functionality as needed.
type skillsDao struct {
	*internal.SkillsDao
}

var (
	// Skills is a globally accessible object for table skills operations.
	Skills = skillsDao{internal.NewSkillsDao()}
)

// Add your custom methods and functionality below.
