// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/cicbyte/aic/internal/dao/internal"
)

// skillFilesDao is the data access object for the table skill_files.
// You can define custom methods on it to extend its functionality as needed.
type skillFilesDao struct {
	*internal.SkillFilesDao
}

var (
	// SkillFiles is a globally accessible object for table skill_files operations.
	SkillFiles = skillFilesDao{internal.NewSkillFilesDao()}
)

// Add your custom methods and functionality below.
